services:
  suporte-da-galera:
    container_name: suporte-da-galera
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # expõe somente o frontend
    ports:
      - "3000:3000"

    environment:
      # 🔧 Backend
      NODE_ENV: production
      PORT: 5000
      DEBUG: "*"
      DATABASE_URL: postgresql://postgres:postgres@host:5432/gamer_support_db
      TOKEN_SECRET: your_token_secret_here
      TOKEN_EXPIRES_IN: 15m
      REFRESH_TOKEN_SECRET: your_refresh_secret_here
      REFRESH_TOKEN_EXPIRES_IN: 7d
      TOKEN_ISSUER: SuporteDaGalera

      # 💅 Frontend
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000

    # Healthcheck do backend (Express)
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/api/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    # Se precisar de banco no mesmo compose (opcional)
    # depends_on:
    #   - postgres

    # networks:
    #   - internal
# networks:
#   internal:
#     driver: bridge
