# API URL
@apiUrl = http://localhost:5000/api

# Access Token
@accessToken = <your_access_token_here>

# Cookie: Refresh Token
@refreshToken = <your_refresh_token_here>

### User Sign Up
POST {{apiUrl}}/v1/auth/sign-up
Content-Type: application/json

{
  "username": "user-02",
  "email": "user-02@example.com",
  "password": "password123"
}

### User Sign In
POST {{apiUrl}}/v1/auth/sign-in
Content-Type: application/json

{
  "email": "user-02@example.com",
  "password": "password123"
}

### Get Current User Info
GET {{apiUrl}}/v1/auth/me
Authorization: Bearer {{accessToken}}

### User Logout
GET {{apiUrl}}/v1/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}}

### Refresh Access Token
GET {{apiUrl}}/v1/auth/refresh-token
