# API URL
@apiUrl = http://localhost:5000/api

# Access Token
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZ3V6MnV5bjAwMDJyb25tbWl3dTA4anQiLCJlbWFpbCI6InVzZXItMDJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA3MTMwNDksImV4cCI6MTc2MDcxMzk0OSwiaXNzIjoiZ2FtZXItc3VwcG9ydC1hcHAifQ.N1F0rTSlyOnzR-_6A2jfzOazkvgRffRIKcb7hVHQ7Dw

# Cookie: Refresh Token
@refreshToken = refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZ3V6MnV5bjAwMDJyb25tbWl3dTA4anQiLCJlbWFpbCI6InVzZXItMDJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA3MTMyMjcsImV4cCI6MTc2MTMxODAyNywiaXNzIjoiZ2FtZXItc3VwcG9ydC1hcHAiLCJqdGkiOiJmYjNiNWVlMC00NGRjLTQyMDQtYWUyYS0wMDYyMzEzYzI3ZmQifQ.puHqQwpxIlXfzOCbik3fl5nNnD5EG0-lVnoWf70Jmkk; Max-Age=604800; Path=/; Expires=Fri, 24 Oct 2025 15:00:27 GMT; HttpOnly; Secure; SameSite=Lax

### User Sign Up
POST {{apiUrl}}/v1/auth/sign-up
Content-Type: application/json

{
  "username": "user-02",
  "email": "user-02@example.com",
  "password": "password123"
}

### User Sign In
POST {{apiUrl}}/v1/auth/sign-in
Content-Type: application/json

{
  "email": "user-02@example.com",
  "password": "password123"
}

### Get Current User Info
GET {{apiUrl}}/v1/auth/me
Authorization: Bearer {{accessToken}}

### User Logout
GET {{apiUrl}}/v1/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}}

### Refresh Access Token
GET {{apiUrl}}/v1/auth/refresh-token
