# API URL
@apiUrl = http://localhost:5000/api

#ticket ID
@ticketId = <your_ticket_id_here>

# Access Token
@accessToken = <your_access_token_here>

### Create Ticket
POST {{apiUrl}}/v1/tickets
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Issue with Game X",
  "game": "Game X",
  "description": "I'm experiencing crashes when I try to launch Game X.",
  "urgency": "SUAVE",
  "status": "ABERTO"
}

### Get Ticket by ID
GET {{apiUrl}}/v1/tickets/{{ticketId}}

### Get All Tickets
GET {{apiUrl}}/v1/tickets

### Add Comment to Ticket
PUT {{apiUrl}}/v1/tickets/{{ticketId}}/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "message": "I'm experiencing crashes when I try to launch Game X."
}

### Delete Ticket
DELETE {{apiUrl}}/v1/tickets/{{ticketId}}
Authorization: Bearer {{accessToken}}